"""Compare candidate base-model tokenizers on the confirmed Kinyarwanda examples.

Loads tokenizer files only (a few MB, no model weights), so it runs on CPU.
Gated models are skipped with a note unless HF_TOKEN grants access.

Usage:
    python scripts/compare_tokenizers.py [model_id ...]
"""

from __future__ import annotations

from pathlib import Path
import os
import sys

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from kinyalm.data.examples import TextExample, load_tsv_examples
from kinyalm.tokenization.metrics import (
    TokenizationStats,
    average_tokens_per_word,
    summarize_many,
)

EXAMPLES_PATH = REPO_ROOT / "docs" / "tokenizer" / "eval-examples.tsv"
REPORT_PATH = REPO_ROOT / "docs" / "tokenizer" / "base-model-tokenizer-comparison.md"

DEFAULT_MODELS = [
    "CohereLabs/aya-expanse-8b",
    "google/gemma-2-9b",
    "Qwen/Qwen2.5-7B",
]

# Single words whose piece breakdown shows whether noun-class prefixes and
# verb morphology survive tokenization.
PIECE_PROBE_IDS = [
    "teacher_vocab",
    "noun_class1_vowel_sg",
    "noun_class7_vowel_sg",
    "noun_class8_vowel_pl",
    "verb_present_1sg",
    "verb_past_1pl",
    "verb_negative_complex",
    "apostrophe_check",
]


def load_confirmed_examples() -> list[TextExample]:
    examples = load_tsv_examples(EXAMPLES_PATH)
    return [item for item in examples if item.status == "confirmed"]


def try_load_tokenizer(model_id: str):
    from transformers import AutoTokenizer

    token = os.environ.get("HF_TOKEN") or None
    try:
        return AutoTokenizer.from_pretrained(model_id, token=token), None
    except Exception as error:  # gated repo, network, or auth failure
        return None, f"{type(error).__name__}: {error}"


def collect_stats(
    tokenizer, examples: list[TextExample]
) -> dict[str, list[TokenizationStats]]:
    """Group stats by example category; key "all" holds every example."""

    def encode(text: str) -> list[int]:
        return tokenizer.encode(text, add_special_tokens=False)

    grouped: dict[str, list[TokenizationStats]] = {"all": []}
    for example in examples:
        stats = summarize_many([example.text], encode)[0]
        grouped["all"].append(stats)
        grouped.setdefault(example.category, []).append(stats)
    return grouped


def format_pieces(tokenizer, text: str) -> str:
    pieces = tokenizer.tokenize(text)
    return " | ".join(piece.replace("|", "\\|") for piece in pieces)


def main() -> int:
    model_ids = sys.argv[1:] or DEFAULT_MODELS
    examples = load_confirmed_examples()
    if not examples:
        print("no confirmed examples found; run aborted")
        return 1

    probe_examples = [item for item in examples if item.id in PIECE_PROBE_IDS]
    lines: list[str] = []
    lines.append("# Base-Model Tokenizer Comparison")
    lines.append("")
    lines.append(
        f"Generated by `scripts/compare_tokenizers.py` over the "
        f"{len(examples)} confirmed examples in `docs/tokenizer/eval-examples.tsv`."
    )
    lines.append("")
    lines.append(
        "Lower tokens/word is more compact. Piece breakdowns show whether "
        "noun-class prefixes and verb morphology survive tokenization."
    )
    lines.append("")

    summary_rows: list[str] = []
    skipped: list[str] = []
    loaded: list[tuple[str, object]] = []

    for model_id in model_ids:
        print(f"loading tokenizer: {model_id}")
        tokenizer, error = try_load_tokenizer(model_id)
        if tokenizer is None:
            print(f"  skipped ({error.splitlines()[0][:120]})")
            skipped.append(f"- `{model_id}` — could not load: {error.splitlines()[0]}")
            continue
        loaded.append((model_id, tokenizer))

        grouped = collect_stats(tokenizer, examples)
        overall = average_tokens_per_word(grouped["all"])
        morphology = average_tokens_per_word(grouped.get("morphology", []))
        worst = max(grouped["all"], key=lambda item: item.tokens_per_word)
        summary_rows.append(
            f"| `{model_id}` | {len(tokenizer)} | {overall:.2f} | {morphology:.2f} "
            f"| {worst.text} ({worst.token_count} tokens) |"
        )
        print(f"  ok: {overall:.2f} tokens/word overall, {morphology:.2f} on morphology")

    lines.append("## Summary")
    lines.append("")
    lines.append(
        "| Tokenizer | Vocab size | Tokens/word (all) | Tokens/word (morphology) "
        "| Most fragmented example |"
    )
    lines.append("| --- | --- | --- | --- | --- |")
    lines.extend(summary_rows)
    lines.append("")

    if skipped:
        lines.append("## Not evaluated")
        lines.append("")
        lines.extend(skipped)
        lines.append("")

    if loaded:
        lines.append("## Piece breakdowns on morphology probes")
        lines.append("")
        for example in probe_examples:
            lines.append(f"### {example.text}")
            lines.append("")
            lines.append(f"{example.notes}")
            lines.append("")
            lines.append("| Tokenizer | Pieces |")
            lines.append("| --- | --- |")
            for model_id, tokenizer in loaded:
                lines.append(f"| `{model_id}` | {format_pieces(tokenizer, example.text)} |")
            lines.append("")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"report written: {REPORT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
